name: Tomlify Unit Tests
run-name: ${{ github.actor }} is running unit tests
on: [push]
jobs:
  Basic-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.17"
      - run: uv --version
      - name: Install Just 
        uses: extractions/setup-just@v3
      - run: just --version
      - name: Set up Python
        run: uv python install
      - run: uv run python --version
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run Unit tests
        run: just test 
      - name: Lint the project
        run: just lint
      - name: Typecheck the project
        run: just typecheck
